import turtle as t
import time
t.tracer(False)
m=t.Shape('compound')
f=t.Shape('compound')
s=t.Shape('compound')
m1 = ((-15,2),(150,2),(150,-2),(-15,-2))
f1 = ((-10,3),(130,3),(130,-3),(-10,-3))
s1 = ((-5,4),(60,4),(60,-4),(-5,-4))
m.addcomponent(m1,'black','black')
f.addcomponent(f1,'black','black')
s.addcomponent(s1,'black','black')
t.register_shape('ss',s)
t.register_shape('ff',f)
t.register_shape('mm',m)
print(t.getshapes())

ss=t.Turtle(shape='ss')
ff=t.Turtle(shape='ff')
mm=t.Turtle(shape='mm')
t.penup()
t.goto(0,200)
t.pendown()
t.pensize(5)
n = 1
for i in range(60):
    if i%5 == 4:
        t.circle(-200, 6)
        t.right(90)
        t.forward(20)
        t.penup()
        t.forward(30)
        t.setx(t.xcor()-10)
        t.sety(t.ycor() - 10)
        t.write(str(n),font=('黑体',24,'bold'))
        t.setx(t.xcor() + 10)
        t.sety(t.ycor() + 10)
        t.forward(-30)
        t.pendown()
        t.forward(-20)
        t.right(-90)
        n += 1
    else:
        t.circle(-200,6)
        t.right(90)
        t.forward(10)
        t.forward(-10)
        t.right(-90)
while True:
        mm.setheading(180-int(time.ctime()[-7:-5])*6)
        ff.setheading(180 - int(time.ctime()[-10:-8])*6)
        ss.setheading(180 - int(time.ctime()[-13:-11])*30-int(time.ctime()[-10:-8])/2)
        time.sleep(1)
        t.update()
