import turtle as t
screen=t.Screen()
t.penup()
def u(f,d):
    t.setheading(f)
    t.forward(d)
    t.update()
def p(x,y):
    a.clear()
    t.goto(x,y)
    a.goto(t.xcor()+50,t.ycor()+60)
    a.write('我叫:%s,身高：%s'%(name,tall))
    t.update()
t.addshape('cxk.gif')
print(t.getshapes())
t.shape('cxk.gif')
t.onkey(lambda :u(90,10),'Up')
t.onkey(lambda :u(270,10),'Down')
t.onkey(lambda :u(180,10),'Left')
t.onkey(lambda :u(0,10),'Right')
v=screen.onscreenclick(p)
a=t.Turtle()
a.penup()
name=t.textinput('your name','name:')
tall=t.numinput('how tall','tall',1.7,0.55,2.8)
t.update()
t.listen()
t.mainloop()